---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-jellyfin-config
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes: [ "ReadWriteOnce" ]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  claimRef:
    namespace: jellyfin         # <-- your PVC namespace
    name: jellyfin-config
  hostPath:
    path: /mnt/data/jellyfin/config   # <-- writable path on the node
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-jellyfin-media
spec:
  capacity:
    storage: 25Gi
  volumeMode: Filesystem
  accessModes: [ "ReadWriteOnce" ]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  claimRef:
    namespace: jellyfin
    name: jellyfin-media
  hostPath:
    path: /mnt/data/jellyfin/media    # <-- writable path on the node
    type: DirectoryOrCreate
